# run: conda env create --file environment.yml
name: ynet
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - imageio
  - ipython
  - matplotlib
  - numpy
  - opencv
  - flake8
  - python=3.8.5
  - scipy
  - tensorboard
  - torchvision
  - tqdm
  - pyyaml
  - scikit-image
