# run: conda env create --file environment.yml
name: ynet
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2
  - pytorch=1.5
  - imageio
  - ipython
  - matplotlib
  - numpy
  - opencv
  - flake8
  - python >=3.7
  - scipy
  - tensorboard
  - torchvision
  - tqdm
  - pyyaml
  - scikit-image