exp_info:
  TB_comment: "no_og_data"

data:
  DSDataset_size: 150
  YITDataset1_size: 60
  YITDataset3_size: 20
  loss_param:
    - "10" # w0
    - "5" # sigma
  trainingSets:
    - DSDataset
    - YITDataset1
    - YITDataset3
  testingSets:
    - DSDataset
    - YITDataset1
    - YITDataset3

train_param:
  k: 5
  toResume: "False"
  normtype: 3
  allDatasets: "True"
  end: 1000
  learning_rate: 0.01
  momentum: 0.9
  crop_size: 256
  no_og_data: False
  random_flip: True
  random_rotate: True
  random_crop: True
  batch_size: 1

model:
  folderpath: ./SavedModels/
  modelname: ynet3.pt
